### ISSUE TITLE
Filter MAIA annotations before insert

### ISSUE THREAD

**Issue by mzur** [biigle/maia#121]
https://github.com/biigle/maia/blob/e6bb111590ff55c95bb4401aab6948730e353b00/src/Jobs/JobResponse.php#L75-L88

There was an error where an image that MAIA generated annotations for was deleted in the meantime. The image IDs should be checked after `createMaiaAnnotation()` and before `insertAnnotationChunk()` and annotations of missing images should be removed. Also create a test case for this.

**Comment by lehecht** [comment]
@mzur 
Is this issue still up-to-date? I cannot find JobResponse.php on the master branch.
