### ISSUE TITLE
Job #168 failed novelty detection

### ISSUE THREAD

**Issue by charleygros** [biigle/maia#55]
Hi @mzur,

I have received the following notification:
```
MAIA job 168 failed during novelty detection. Please notify the BIIGLE administrators.
```

Please find here below the parameters:
![image](https://user-images.githubusercontent.com/14353425/89370889-269ff380-d725-11ea-81f7-bbf377ac9ddd.png)

Could you please help me?
Cheers,
Charley

**Comment by charleygros** [comment]
I guess that was because of `patch_size=99` since when running with the default `39` it works well.

**Comment by mzur** [comment]
That`s correct, a patch size of 99 was too much for the relatively large images and the GPU memory we have available. The memory consumption should adapt to the used parameters but this is done with an imprecise heuristic which can sometimes result in errors like these.

**Comment by charleygros** [comment]
Thanks for your insights @mzur , appreciate this!
