### ISSUE TITLE
Maia data import

### ISSUE THREAD

**Issue by dlangenk** [biigle/maia#95]
It would be great to be able to import data into Maia using the API. This way Maia could be used as a visualization device for external algorithms and would make the integration of new methods more easy and flexible.

**Comment by mzur** [comment]
This could be done as follows: Offer an option similar to the "training data method" to "upload detections" in the form to create a new MAIA job. Users can upload a COCO file (or iFDO?) here. When the job is submitted the uploaded file is parsed and annotation candidates are generated directly from the file. Then the job proceeds to the last stage, skipping novelty detection and object detection. It should still generate feature files for image sorting (#27).

This option should support more shapes than just circles. This must be supported in the "refine" view of the annotation candidates, which will probably involve most work required to implement this feature.

**Comment by dlangenk** [comment]
If it is not a xor between COCO and iFDO I don't mind 😉. But otherwise an additional tool has to be written to convert a fiftyone/mmdetection/detectron/... dataset to iFDO and then the usage of this feature is limited to some degree.

**Comment by mzur** [comment]
This can use the new metadata parsers of https://github.com/biigle/core/pull/709 We can implement a COCO parser that can both be used in the volume creation flow as well as the MAIA upload. This way we can support iFDO (and maybe other formats) for the MAIA upload, too.

**Comment by mzur** [comment]
Thinking about this... maybe this will become obsolete with the new create volume flow? If you generate offline detections you can simply upload them as a new volume and use Largo for review? You can even upload and review predicted classes this way.
