### ISSUE TITLE
Framework change to mmdet

### ISSUE THREAD

**Issue by dlangenk** [biigle/maia#96]
We could change the detection framework to [mmdet](https://github.com/open-mmlab/mmdetection), which would have multiple benefits.

- likely to be faster and more memory efficient
- possibility of being more flexible with algorithm choice
- things like different augmentations, losses, ...

**Comment by mzur** [comment]
We've come to the point where we can't update TensorFlow any more without breaking the Mask R-CNN implementation of MAIA. While the code still runs, the detection output is wrong somehow. The current TF version has [several security vulnerabilities](https://github.com/biigle/maia/security/dependabot).

I think we should make the move to mmdet and maybe just use a simple Faster R-CNN as a starting point. We should compare detection performance with the original MAIA implementation but it *should* be similar. We can then experiment with the advanced features of mmdet at some later point.

The move to mmdet and PyTorch has the additional advantage that it's compatible with DINO, which we plan to use to sort image thumbnails.

**Comment by dlangenk** [comment]
What about dropping the autoencoder and using DINO right away or do you want to keep it for compatibility?
It might be possible to convert it to onnx (https://github.com/onnx/tensorflow-onnx) and back to pytorch (https://github.com/ToriML/onnx2pytorch) but you also might run into some problems.

If you don't want to use Mask R-CNN instance segmentation I agree that Faster R-CNN or YOLO might be a better solution because it uses less ressources.

**Comment by mzur** [comment]
> What about dropping the autoencoder and using DINO right away or do you want to keep it for compatibility?

I would like to keep the current feature set in BIIGLE.

> It might be possible to convert it to onnx [...]

That only works for models, right? You still have to implement the code in the new framework. For MAIA novelty detection, the autoencoder is trained from scratch each time, so no model is reused at all.

**Comment by dlangenk** [comment]
To my knowledge it is not only the weights but also the operations (the model architecture) which is transformed, so it should work.

**Comment by mzur** [comment]
I managed to get MAIA running on an older version of TensorFlow again, so it is functional right now. We should still make the change to a more maintainable implementation. Maybe as part of the [hackathon](https://github.com/orgs/biigle/discussions/428).

**Comment by dlangenk** [comment]
I guess it might be a good idea if you could gather some like plug in points/interfaces where code has to be injected such as - exchange noveltydetection.py it receives parameter1,2,3,4 via command line and outputs json to stdout

**Comment by mzur** [comment]
Most updates are required for the Python scripts in [`src/resources/scripts`](https://github.com/biigle/maia/tree/master/src/resources/scripts). That is, most of them probably have to be replaced entriely. There is one directory for novelty detection and one for instance segmentation (which is just object detection, really).

Novelty detection is handled by the [`NoveltyDetectionRequest`](https://github.com/biigle/maia/blob/cafa1df110f29e63e4777129aeb732c73972aa8b/src/Jobs/NoveltyDetectionRequest.php) job which creates a [JSON file](https://github.com/biigle/maia/blob/cafa1df110f29e63e4777129aeb732c73972aa8b/src/Jobs/NoveltyDetectionRequest.php#L35) that is passed on to the [`DetectionRunner`](https://github.com/biigle/maia/blob/cafa1df110f29e63e4777129aeb732c73972aa8b/src/resources/scripts/novelty-detection/DetectionRunner.py). This script runs the novelty detection, which in turn outputs one JSON file with detection locations for each input image to the temporary directory. These JSON files are parsed [here](https://github.com/biigle/maia/blob/cafa1df110f29e63e4777129aeb732c73972aa8b/src/Jobs/JobRequest.php#L221-L241).

Instance segmentation is handled by the [`InstanceSegmentationRequest`](https://github.com/biigle/maia/blob/cafa1df110f29e63e4777129aeb732c73972aa8b/src/Jobs/InstanceSegmentationRequest.php) job. It runs multiple steps:
1. [`generateDataset`](https://github.com/biigle/maia/blob/cafa1df110f29e63e4777129aeb732c73972aa8b/src/Jobs/InstanceSegmentationRequest.php#L129): A JSON file is [created](https://github.com/biigle/maia/blob/cafa1df110f29e63e4777129aeb732c73972aa8b/src/Jobs/InstanceSegmentationRequest.php#L140), containing information on the original training image files and training proposals, and passed on to the [`DatasetGenerator`](https://github.com/biigle/maia/blob/cafa1df110f29e63e4777129aeb732c73972aa8b/src/resources/scripts/instance-segmentation/DatasetGenerator.py). This script extracts image crops of each annotation and generates the mask files for each crop that are required to train Mask R-CNN. Information about these files is returned in an [output JSON file](https://github.com/biigle/maia/blob/cafa1df110f29e63e4777129aeb732c73972aa8b/src/Jobs/InstanceSegmentationRequest.php#L131).

2. [`performTraining`](https://github.com/biigle/maia/blob/cafa1df110f29e63e4777129aeb732c73972aa8b/src/Jobs/InstanceSegmentationRequest.php#L184): A JSON file is [created](https://github.com/biigle/maia/blob/cafa1df110f29e63e4777129aeb732c73972aa8b/src/Jobs/InstanceSegmentationRequest.php#L188), containing information on the training scheme etc., and is passed on (together with the output JSON of the previous step) to the [`TrainingRunner`](https://github.com/biigle/maia/blob/cafa1df110f29e63e4777129aeb732c73972aa8b/src/resources/scripts/instance-segmentation/TrainingRunner.py). This script runs the training of Mask R-CNN and returns another [output JSON](https://github.com/biigle/maia/blob/cafa1df110f29e63e4777129aeb732c73972aa8b/src/Jobs/InstanceSegmentationRequest.php#L186) containing information on the saved file of the trained model.

3. [`performInference`](https://github.com/biigle/maia/blob/cafa1df110f29e63e4777129aeb732c73972aa8b/src/Jobs/InstanceSegmentationRequest.php#L243): A JSON file is [created](https://github.com/biigle/maia/blob/cafa1df110f29e63e4777129aeb732c73972aa8b/src/Jobs/InstanceSegmentationRequest.php#L247), containing information on the image files on which inference should be performed, and passed on (together with the output JSONs of the previous steps) to the [`InferenceRunner`](https://github.com/biigle/maia/blob/cafa1df110f29e63e4777129aeb732c73972aa8b/src/resources/scripts/instance-segmentation/InferenceRunner.py). This script runs the inference and returns one JSON file with detection locations for each image (in the same format than the novelty detection) to the temporary directory. These JSON files are parsed with the [same function](https://github.com/biigle/maia/blob/cafa1df110f29e63e4777129aeb732c73972aa8b/src/Jobs/JobRequest.php#L221-L241) than the ones of the novelty detection.
